### PR TITLE
lift cpu limits for mediawiki resources

### PR DESCRIPTION
**Pull request by deer-wmde**
https://phabricator.wikimedia.org/T375874

as a first step we only lift cpu limits for mw resources and will observe the effect

### CODE REVIEW

**Review by dati18 — COMMENTED** [review]
In my opinion, we should bump more on `production` and less on `staging` since `staging` is not as demanding as `prod`. What do you think?

**Comment by tarrow** [comment]
Generally looks fine to me; I struggled to find some docs saying that 0 === unlimited. I don't suppose you have a reference for that?

**Comment by deer-wmde** [comment]
> Generally looks fine to me; I struggled to find some docs saying that 0 === unlimited. I don't suppose you have a reference for that?

Excellent question, I will verify this on the staging cluster.

**Review by tarrow — APPROVED** [review]

**Comment by tarrow** [comment]
given you're not here I'm gonna ship this now :)

**Pull request merged**
